### Base URL constant
@base_url = http://127.0.0.1:8080

### 接口：tasks
GET {{base_url}}/tasks HTTP/1.1
Content-Type: application/json


### 接口：tasks
POST {{base_url}}/tasks HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "name": "lime",
    "completed": false
}


### 接口：tasks
PUT  {{base_url}}/tasks HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "name": "lijunjun",
    "completed": false
}



### 接口：/tasks/{id}
GET {{base_url}}/tasks/3 HTTP/1.1
Content-Type: application/json


### 接口：/tasks/{id}
DELETE  {{base_url}}/tasks/3 HTTP/1.1
Content-Type: application/json


### 接口： register
POST {{base_url}}/register
Content-Type: application/json

{
    "id": 13,
    "username": "lilime",
    "password": "123456"
}



### 接口： login
POST {{base_url}}/login
Content-Type: application/json

{
    "id": 13,
    "username": "lilime",
    "password": "123456"
}